Global_Messages:
    Enable: true
    Header_And_Footer: true
    Interval: 30
    Prefix: "&7[&6!&7]"
    Header: "&7*&7&m--------------------------------&7*"
    Footer: "&7*&7&m--------------------------------&7*"
    Sound: ''
    Messages:
      - "{Prefix} &6歡迎來到現實生存! &7徒手無法砍樹，請先找礫石獲取燧石。"
      - "{Prefix} &7挖掘礫石獲得&6燧石&7，左鍵點擊石頭獲得&6燧石碎片&7。"
      - "{Prefix} &7破壞樹葉獲取&6木棍&7，收集草獲得&6植物纖維&7製作植物線。"
      - "{Prefix} &7使用&6燧石碎片&7和&6木棍&7製作&6燧石刀&7，這是你的第一個工具。"
      - "{Prefix} &7製作&6燧石斧&7需要&6植物線&7、&6木棍&7和&6燧石碎片&7，然後才能砍伐原木。"
      - "{Prefix} &7獲取木板？放下原木後用&6燧石斧&7右鍵點擊頂部，可能需要多次點擊。"
      - "{Prefix} &7獲取木棍？放下木板後右鍵點擊頂部，同樣可能需要多次點擊。"
      - "{Prefix} &7注意HUD上的&c溫度圈&7和&9口渴條&7，保持中性溫度和水分。"
      - "{Prefix} &7在飲用水前請使用&6木炭過濾器&7淨化水源，避免寄生蟲感染。"
      - "{Prefix} &7想喝水？&7Shift+右鍵點擊水源，或直視天空Shift+左鍵飲用雨水。"
      - "{Prefix} &7製作&6水壺&7可儲存5份飲料，是長途旅行的必備品。"
      - "{Prefix} &7想要高效獲取木材？製作&6鋸子&7後放入合成台處理原木。"
      - "{Prefix} &7可以將&6純淨水&7與&6糖&7和&6水果&7合成果汁，提供更好的水分補充。"
      - "{Prefix} &7使用&6斯巴達武器&7需要先製作各種手柄和桿子，提供專精戰鬥體驗。"
      - "{Prefix} &7不同的&6斯巴達武器&7有不同的攻擊範圍和特性，適合不同戰鬥風格。"
      - "{Prefix} &7&6長矛&7可以投擲並有較長的攻擊距離，適合對付危險生物。"
      - "{Prefix} &7&6迴旋鏢&7是有效的遠程武器，投擲後會自動返回。"
      - "{Prefix} &7收集&6幽靈淤泥&7可製作飾品袋，裝備強力的附魔飾品。"
      - "{Prefix} &7飾品袋中的不同插槽只能放置特定類型的飾品，請查看飾品描述。"
      - "{Prefix} &7溫度管理提示：羊毛護甲保暖、凝膠史萊姆護甲降溫。"
      - "{Prefix} &7在熱帶生物群系攜帶&6水桶&7和穿戴&6凝膠史萊姆護甲&7可有效降溫。"
      - "{Prefix} &7在寒冷生物群系中，&6羊毛護甲&7和&6普通營火&7是保持溫暖的好方法。"
      - "{Prefix} &7&6靈魂營火&7會顯著降低周圍溫度，適合在熱帶地區建造。"
      - "{Prefix} &7在水中遇到&c海蛇&7或&c海妖&7請保持距離，使用遠程武器攻擊。"
      - "{Prefix} &7海妖掉落的&b閃亮鱗片&7和海蛇的&b海蛇鱗片&7可製作潮汐守護者護甲。"
      - "{Prefix} &7想對抗海蛇？至少需要一套附魔鑽石護甲和充足的飾品。"
      - "{Prefix} &c&l警告：&7龍比原版末影龍強大得多，請做足準備再挑戰！"
      - "{Prefix} &7龍有三種不同的品種，每種品種還分為四種變種。"
      - "{Prefix} &7龍除了有類似末影龍的攻擊外，還有特殊的&c龍息&7和&c爆炸&7攻擊。"
      - "{Prefix} &7挑戰龍前至少需要附魔鑽石護甲，最好是下界合金，以及裝滿的飾品袋。"
      - "{Prefix} &7溫馨提示：在溫帶生物群系建造基地以避免極端溫度變化。"
      - "{Prefix} &7避開岩漿池或大片冰塊等熱源或冷源，以免影響基地溫度。"
      - "{Prefix} &7大多數護甲套裝在穿著時會調節溫度，幫助應對環境挑戰。"
      - "{Prefix} &7如果你無法找到海妖，可以編輯iceandfire.yml配置文件，修改掉落物設置。"
      - "{Prefix} &7若有任何疑問，請加入Discord伺服器尋求幫助：&9discord.gg/mMt3f4usqK"
      - "{Prefix} &7查看Wiki可獲取更多遊戲指南和提示：&9github.com/ValMobile/RealisticSurvival/wiki"
      - "{Prefix} &7親愛的&c{player}&7，目前有&c{online}&7位玩家正在挑戰現實生存！"