Global_Messages:
    Enable: true
    Header_And_Footer: true
    Interval: 30
    Prefix: "&7[&6!&7]"
    Header: "&7*&7&m--------------------------------&7*"
    Footer: "&7*&7&m--------------------------------&7*"
    Sound: ''
    Random: false
    Messages:
      - "{Prefix} &6測試訊息1"
      - "{Prefix} &7測試訊息2"